FROM alpine:3.4

#
# v1 dex-api
#

LABEL org.dockerland.dex.api="v1"

# defaults you may override, see <@TODO URL>
# LABEL org.dockerland.dex.home="~"
# LABEL org.dockerland.dex.workspace="\$(pwd)"
# LABEL org.dockerland.dex.docker-flags="-i \$dex-x11-flags"
# LABEL org.dockerland.dex.docker-entrypoint=""
# LABEL org.dockerland.dex.docker-entrypoint="=""

#
# alpine image
#

CMD echo "ALPINE_RELEASE=$(cat /etc/alpine-release)" ; printenv
