FROM debian:jessie

#
# v1 dex-api
#

LABEL org.dockerland.dex.api="v1"

# defaults you may override, see <@TODO URL>
#
# LABEL org.dockerland.dex.host_home="~"
# LABEL org.dockerland.dex.host_workspace="\$(pwd)"
# LABEL org.dockerland.dex.docker_flags="-i \$DEX_X11_FLAGS"
#


#
# debian image
#

CMD echo "DEBIAN_RELEASE=$(cat /etc/debian_version)" ; printenv
