FROM alpine:3.4

RUN apk add --no-cache \
  docker

#
# v1 dex-api
#

LABEL \
  org.dockerland.dex.api="v1" \
  org.dockerland.dex.host_docker=rw

#
# debian image
#

CMD echo "ALPINE_RELEASE=$(cat /etc/alpine-release)" ; printenv
